# Generated by Django 5.2.7 on 2025-11-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='passenger_phone',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
