# Generated by Django 5.2.7 on 2025-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_bookings_passenger_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
